# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 805a862afce4195c7f9176d63ecd238067949b4cddc600d71c8c9c501fa1ae95cb1aedb514cde8031a6a5656eeea88b28fd499ddb9bcc933f2130baf71b17dcb

test:
  secret_key_base: 363389245de8d950feeaa6829d2a34465983f262ccd99d736651370feadc91a5941433c85e626444127fb5d89ef1e99f99d4c8b29d8ee95066ed1b9ee658e873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
